=== engineeringtaharica/Test_Repo/RX3000 Updater/Data/DataSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="values">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="Data">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="ID" type="xs:unsignedByte" />
              <xs:element name="Value" type="xs:string" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== engineeringtaharica/Test_Repo/RX3000 Updater/Data/APNData.xml
<?xml version="1.0" encoding="utf-8" ?>

<values xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DataSchema.xsd">
  <Data>
    <ID>0</ID>
    <Value>Pick a value</Value>
  </Data>
  <Data>
    <ID>1</ID>
    <Value>wyless.net</Value>
  </Data>
  <Data>
    <ID>2</ID>
    <Value>gprs02.motient.net</Value>
  </Data>
  <Data>
    <ID>3</ID>
    <Value>telargo.t-mobile.com;username=Ons9677;password=03364c7a</Value>
  </Data>
  <Data>
    <ID>4</ID>
    <Value>o2.wyless.net;username=Ons9677;password=03364c7a</Value>
  </Data>
  <Data>
    <ID>5</ID>
    <Value>CMNET</Value>
  </Data>
  <Data>
    <ID>6</ID>
    <Value>internet.com;username=wapuser1;password=wap</Value>
  </Data>
  <Data>
    <ID>7</ID>
    <Value>imovil.entelpcs.cl;username=entelpcs;password=entelpcs</Value>
  </Data>
  <Data>
    <ID>8</ID>
    <Value>internet;username=internet;password=internet</Value>
  </Data>
  <Data>
    <ID>9</ID>
    <Value>internet</Value>
  </Data>
  <Data>
    <ID>10</ID>
    <Value>internet.t-d1.de;username=t-d1;password=t-d1</Value>
  </Data>
  <Data>
    <ID>11</ID>
    <Value>vivo;username=vivo;password=vivo</Value>
  </Data>
  <Data>
    <ID>12</ID>
    <Value>isp.cingular;username=ISP@CINGULARGPRS.COM;password=CINGULAR1</Value>
  </Data>
  <Data>
    <ID>13</ID>
    <Value>internet2.voicestream.com</Value>
  </Data>
</values>

=== engineeringtaharica/Test_Repo/RX3000 Updater/Data/OSERData.xml
<?xml version="1.0" encoding="utf-8" ?>
<values xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DataSchema.xsd">
  <Data>
    <ID>0</ID>
    <Value>'?' - CMD_LOADER_INFO</Value>
  </Data>
  <Data>
    <ID>1</ID>
    <Value>'@' - CMD_IDLE</Value>
  </Data>
  <Data>
    <ID>2</ID>
    <Value>'A' - CMD_GET_INFO</Value>
  </Data>
  <Data>
    <ID>3</ID>
    <Value>'B' - CMD_WRITE_TO_ADDR</Value>
  </Data>
  <Data>
    <ID>4</ID>
    <Value>'C' - CMD_GET_CONVERSION</Value>
  </Data>
  <Data>
    <ID>5</ID>
    <Value>'D' - CMD_STOP_LOGGING</Value>
  </Data>
  <Data>
    <ID>6</ID>
    <Value>'E' - CMD_READ_AT_ADDR</Value>
  </Data>
  <Data>
    <ID>7</ID>
    <Value>'F' - CMD_LAUNCH</Value>
  </Data>
  <Data>
    <ID>8</ID>
    <Value>'G' - CMD_BATTERY</Value>
  </Data>
  <Data>
    <ID>9</ID>
    <Value>'H' - CMD_LOW_POWER</Value>
  </Data>
  <Data>
    <ID>10</ID>
    <Value>'I' - CMD_TERMINATE_COMM</Value>
  </Data>
  <Data>
    <ID>11</ID>
    <Value>'J' - CMD_WRITE_PROTECT_OFF</Value>
  </Data>
  <Data>
    <ID>12</ID>
    <Value>'K' - CMD_GET_RTC</Value>
  </Data>
  <Data>
    <ID>13</ID>
    <Value>'L' - CMD_SET_RTC</Value>
  </Data>
  <Data>
    <ID>14</ID>
    <Value>'M' - CMD_GET_DATAFILE_PTR</Value>
  </Data>
  <Data>
    <ID>15</ID>
    <Value>'N' - CMD_SET_DATAFILE_PTR</Value>
  </Data>
  <Data>
    <ID>16</ID>
    <Value>'O' - CMD_GET_LOGGER_STATUS</Value>
  </Data>
  <Data>
    <ID>17</ID>
    <Value>'P' - CMD_GET_SENSOR_HEADER</Value>
  </Data>
  <Data>
    <ID>18</ID>
    <Value>'Q' - CMD_ATTACHED_SENSORS</Value>
  </Data>
  <Data>
    <ID>19</ID>
    <Value>'R' - CMD_ASSIGN_SENSORS</Value>
  </Data>
  <Data>
    <ID>20</ID>
    <Value>'S' - CMD_OBUS_ERROR</Value>
  </Data>
  <Data>
    <ID>21</ID>
    <Value>'T' - CMD_LED_TEST</Value>
  </Data>
  <Data>
    <ID>22</ID>
    <Value>'U' - CMD_CALIBRATE_RTC</Value>
  </Data>
  <Data>
    <ID>23</ID>
    <Value>'V' - CMD_SENS_MEAS_ASCII</Value>
  </Data>
  <Data>
    <ID>24</ID>
    <Value>'V' - CMD_WRITE_PROGRAM_TO_ADDR</Value>
  </Data>
  <Data>
    <ID>25</ID>
    <Value>'W' - CMD_READ_FLASH_PROGRAM</Value>
  </Data>
  <Data>
    <ID>26</ID>
    <Value>'W' - CMD_SENS_NAME_ASCII</Value>
  </Data>
  <Data>
    <ID>27</ID>
    <Value>'X' - CMD_RESTART</Value>
  </Data>
  <Data>
    <ID>28</ID>
    <Value>'Y' - CMD_WRITE_TO_OB_EE_ADDR</Value>
  </Data>
  <Data>
    <ID>29</ID>
    <Value>'Z' - CMD_READ_OB_EE_AT_ADDR</Value>
  </Data>
  <Data>
    <ID>30</ID>
    <Value>'[' - CMD_SYS_STATUS</Value>
  </Data>
  <Data>
    <ID>31</ID>
    <Value>'a' - CMD_SET_ALARM_PARAM</Value>
  </Data>
  <Data>
    <ID>32</ID>
    <Value>'b' - CMD_GET_ALARM_PARAM</Value>
  </Data>
  <Data>
    <ID>33</ID>
    <Value>'c' - CMD_CURRENT_READING16</Value>
  </Data>
  <Data>
    <ID>34</ID>
    <Value>'d' - CMD_CURRENT_ALLREADINGS</Value>
  </Data>
  <Data>
    <ID>35</ID>
    <Value>'e' - CMD_CLEAR_ALARM_PARAM</Value>
  </Data>
  <Data>
    <ID>36</ID>
    <Value>'f' - CMD_BATT_TENBIT</Value>
  </Data>
  <Data>
    <ID>37</ID>
    <Value>'g' - CMD_CONTROL_ALARM_LED</Value>
  </Data>
</values>

=== engineeringtaharica/Test_Repo/RX3000 Updater/Data/IPData.xml
<?xml version="1.0" encoding="utf-8" ?>
<values xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DataSchema.xsd">
  <Data>
    <ID>0</ID>
    <Value>Pick a value</Value>
  </Data>
  <Data>
    <ID>1</ID>
    <Value>dil.hobolink.com:54228</Value>
  </Data>
  <Data>
    <ID>2</ID>
    <Value>dil.hobolink.com:54328</Value>
  </Data>
  <Data>
    <ID>3</ID>
    <Value>208.85.146.151:54328</Value>
  </Data>
  <Data>
    <ID>4</ID>
    <Value>dil.hobolink.com:54225</Value>
  </Data>
  <Data>
    <ID>5</ID>
    <Value>dil.hobolink.com:54325</Value>
  </Data>
  <Data>
    <ID>6</ID>
    <Value>208.85.146.151:54325</Value>
  </Data>
</values>

=== engineeringtaharica/Test_Repo/RX3000 Updater/Data/HTData.xml
<?xml version="1.0" encoding="utf-8" ?>
<values xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DataSchema.xsd">
  <Data>
    <ID>0</ID>
    <Value>Get_SYSID</Value>
  </Data>
  <Data>
    <ID>1</ID>
    <Value>Get_HTDAT</Value>
  </Data>
  <Data>
    <ID>2</ID>
    <Value>Open_HT_sys</Value>
  </Data>
  <Data>
    <ID>3</ID>
    <Value>Close_HT_sys</Value>
  </Data>
  <Data>
    <ID>4</ID>
    <Value>Restart_HT_sys</Value>
  </Data>
  <Data>
    <ID>5</ID>
    <Value>Session_Open</Value>
  </Data>
  <Data>
    <ID>6</ID>
    <Value>Session_Close</Value>
  </Data>
  <Data>
    <ID>7</ID>
    <Value>Set_Operational_Parameters</Value>
  </Data>
  <Data>
    <ID>8</ID>
    <Value>Get_Operational_Parameters</Value>
  </Data>
  <Data>
    <ID>9</ID>
    <Value>Get_Operational_Statistics</Value>
  </Data>
  <Data>
    <ID>10</ID>
    <Value>Set_Timestamp</Value>
  </Data>
  <Data>
    <ID>11</ID>
    <Value>Get_DFP</Value>
  </Data>
  <Data>
    <ID>12</ID>
    <Value>Get_RSSI</Value>
  </Data>
  <Data>
    <ID>13</ID>
    <Value>Write_Serial_Number</Value>
  </Data>
  <Data>
    <ID>14</ID>
    <Value>Set_Plan</Value>
  </Data>
  <Data>
    <ID>15</ID>
    <Value>Get_Plan</Value>
  </Data>
  <Data>
    <ID>16</ID>
    <Value>Get_Protocol</Value>
  </Data>
  <Data>
    <ID>17</ID>
    <Value>OSER_cmd</Value>
  </Data>
  <Data>
    <ID>18</ID>
    <Value>OSER_set_retries</Value>
  </Data>
  <Data>
    <ID>19</ID>
    <Value>OSER_get_retries</Value>
  </Data>
  <Data>
    <ID>20</ID>
    <Value>OSER_multi_read</Value>
  </Data>
  <Data>
    <ID>21</ID>
    <Value>OSER_multi_write</Value>
  </Data>
  <Data>
    <ID>22</ID>
    <Value>OSER_batch</Value>
  </Data>
  <Data>
    <ID>23</ID>
    <Value>Set_local_time</Value>
  </Data>
  <Data>
    <ID>24</ID>
    <Value>Get_local_time</Value>
  </Data>
  <Data>
    <ID>25</ID>
    <Value>Set_host_call_time</Value>
  </Data>
  <Data>
    <ID>26</ID>
    <Value>Get_host_call_time</Value>
  </Data>
  <Data>
    <ID>27</ID>
    <Value>Disable_Host_Contact</Value>
  </Data>
  <Data>
    <ID>28</ID>
    <Value>Get_CGM_info</Value>
  </Data>
  <Data>
    <ID>29</ID>
    <Value>Set_CGM_power_state</Value>
  </Data>
  <Data>
    <ID>30</ID>
    <Value>Get_CGM_power_state</Value>
  </Data>
  <Data>
    <ID>31</ID>
    <Value>Set_Host_IP_Addr</Value>
  </Data>
  <Data>
    <ID>32</ID>
    <Value>Get_Host_IP_Addr</Value>
  </Data>
  <Data>
    <ID>33</ID>
    <Value>Set_SIM_Phone_Num</Value>
  </Data>
  <Data>
    <ID>34</ID>
    <Value>Get_SIM_Phone_Num</Value>
  </Data>
  <Data>
    <ID>35</ID>
    <Value>Start_Java_App</Value>
  </Data>
  <Data>
    <ID>36</ID>
    <Value>Set_Working_File</Value>
  </Data>
  <Data>
    <ID>37</ID>
    <Value>Write_To_File</Value>
  </Data>
  <Data>
    <ID>38</ID>
    <Value>Move_Java_App</Value>
  </Data>
  <Data>
    <ID>39</ID>
    <Value>Finalize_Upload</Value>
  </Data>
  <Data>
    <ID>40</ID>
    <Value>Set_APN_String</Value>
  </Data>
  <Data>
    <ID>41</ID>
    <Value>Get_APN_String</Value>
  </Data>
  <Data>
    <ID>42</ID>
    <Value>Mfg_Data_Request</Value>
  </Data>
  <Data>
    <ID>43</ID>
    <Value>Set_PM_parameters</Value>
  </Data>
  <Data>
    <ID>44</ID>
    <Value>Get_PM_parameters</Value>
  </Data>
  <Data>
    <ID>45</ID>
    <Value>Get_PM_readings</Value>
  </Data>
  <Data>
    <ID>46</ID>
    <Value>Blink_sys_LED</Value>
  </Data>
  <Data>
    <ID>47</ID>
    <Value>Set_log_level</Value>
  </Data>
  <Data>
    <ID>48</ID>
    <Value>Get_log_level</Value>
  </Data>
  <Data>
    <ID>49</ID>
    <Value>Clear_logs</Value>
  </Data>
  <Data>
    <ID>50</ID>
    <Value>Get_log_info</Value>
  </Data>
  <Data>
    <ID>51</ID>
    <Value>Get_log_data</Value>
  </Data>
  <Data>
    <ID>52</ID>
    <Value>Configure_New_Alarm</Value>
  </Data>
  <Data>
    <ID>53</ID>
    <Value>Delete_Alarm_Definitions</Value>
  </Data>
  <Data>
    <ID>54</ID>
    <Value>Enable_Alarm</Value>
  </Data>
  <Data>
    <ID>55</ID>
    <Value>Disable_Alarm</Value>
  </Data>
  <Data>
    <ID>56</ID>
    <Value>Get_Alarm_Info</Value>
  </Data>
  <Data>
    <ID>57</ID>
    <Value>Get_Alarm_Definition</Value>
  </Data>
  <Data>
    <ID>58</ID>
    <Value>Get_Alarm_State</Value>
  </Data>
  <Data>
    <ID>59</ID>
    <Value>Get_Alarm_Value</Value>
  </Data>
  <Data>
    <ID>60</ID>
    <Value>Configure_System_Alarms</Value>
  </Data>
  <Data>
    <ID>61</ID>
    <Value>Set_Default_State</Value>
  </Data>
  <Data>
    <ID>62</ID>
    <Value>Get_Default_State</Value>
  </Data>
  <Data>
    <ID>63</ID>
    <Value>Perform_Relay_Action</Value>
  </Data>
  <Data>
    <ID>64</ID>
    <Value>Get_Relay_State</Value>
  </Data>
  <Data>
    <ID>65</ID>
    <Value>Set_Relay_Pulse_Width</Value>
  </Data>
  <Data>
    <ID>66</ID>
    <Value>Make_GPS_Measurement</Value>
  </Data>
  <Data>
    <ID>67</ID>
    <Value>Turn_GPS_On</Value>
  </Data>
  <Data>
    <ID>68</ID>
    <Value>Turn_GPS_Off</Value>
  </Data>
  <Data>
    <ID>69</ID>
    <Value>Set_Logging_Rate</Value>
  </Data>
  <Data>
    <ID>70</ID>
    <Value>Get_GPS_Log_Info</Value>
  </Data>
  <Data>
    <ID>71</ID>
    <Value>Get_GPS_Data</Value>
  </Data>
  <Data>
    <ID>72</ID>
    <Value>Get_Logging_Rate</Value>
  </Data>
  <Data>
    <ID>73</ID>
    <Value>Boot</Value>
  </Data>
  <Data>
    <ID>74</ID>
    <Value>Write_log</Value>
  </Data>
</values>

=== engineeringtaharica/Test_Repo/RX3000 Updater/Data/PICData.xml
<?xml version="1.0" encoding="utf-8" ?>
<values xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DataSchema.xsd">
  <Data>
    <ID>0</ID><Value>Pick a value</Value>
  </Data>
  <Data>
    <ID>1</ID><Value>FLEX1</Value>
  </Data>
  <Data>
    <ID>2</ID><Value>FLEX2</Value>
  </Data>
  <Data>
    <ID>3</ID><Value>LCD</Value>
  </Data>
  <Data>
    <ID>4</ID><Value>OBUS</Value>
  </Data>
  <Data>
    <ID>5</ID><Value>WSN</Value>
  </Data>
</values>
